In [1]:
import numpy as np
print("the numpy is loaded")
print("NumPy Version:", np.__version__)

the numpy is loaded
NumPy Version: 2.4.6


In [2]:
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
print(array.ndim)
print(array.shape)
#-------------------#

#-------------------#
aray = np.array([[['A', 'B', 'C'],['D', 'E','F'],['G', 'H','I']]
                ,[['J', 'K', 'L'], ['M','N','O'],['P', 'Q', 'R']]
                ,[['S', 'T', 'U'], ['V','W','X'],['Y', 'Z','']]])
word = aray[0, 0, 0]+aray[2, 0, 0]+aray[2, 0, 0]
print(word)
print(aray)
print(aray.ndim)
print(aray.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
ASS
[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' '']]]
3
(3, 3, 3)


In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])
print(array[:,1])

[ 2  6 10 14]


In [6]:
import numpy as np
print(np.zeros((2,4)))
print(np.ones((2,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
import numpy as np
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])
print(arr.ravel())
print(arr.flatten())
print(arr.min())
print(arr.max())
print(arr.argmin())
print(arr.argmax())
print(arr.min(axis=0))
print(arr.min(axis=1))
print(arr.max(axis=0))
print(arr.max(axis=1))
print(arr.argmin(axis=0))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1
16
0
15
[1 2 3 4]
[ 1  5  9 13]
[13 14 15 16]
[ 4  8 12 16]
[0 0 0 0]


In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

#----------------#

a = [1, 2, 3]
b = [4, 5, 6]

print(a + b)
#----------------#
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(np.array([1,2,3]) * 2)

[5 7 9]
[1, 2, 3, 4, 5, 6]
[5 7 9]
[2 4 6]
