In [1]:
import numpy as np
print("the numpy is loaded")
print("NumPy Version:", np.__version__)

the numpy is loaded
NumPy Version: 2.4.6


In [2]:
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
print(array.ndim)
print(array.shape)
#-------------------#

#-------------------#
aray = np.array([[['A', 'B', 'C'],['D', 'E','F'],['G', 'H','I']]
                ,[['J', 'K', 'L'], ['M','N','O'],['P', 'Q', 'R']]
                ,[['S', 'T', 'U'], ['V','W','X'],['Y', 'Z','']]])
word = aray[0, 0, 0]+aray[2, 0, 0]+aray[2, 0, 0]
print(word)
print(aray)
print(aray.ndim)
print(aray.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
ASS
[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' '']]]
3
(3, 3, 3)


In [3]:
import numpy as np
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])
print(array[:,1])

[ 2  6 10 14]
